apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "connect"
spec:
  kprobes:
    - call: "tcp_connect"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchArgs:
            - index: 0
              operator: "NotDAddr"
              values:
                - 127.0.0.1
    - call: "udp_sendmsg"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchArgs:
            - index: 0
              operator: "NotDAddr"
              values:
                - 127.0.0.1
    - call: "udp_recvmsg"
      syscall: false
      args:
      - index: 0
        type: "sock"
      - index: 2
        type: "size_t"
    # - call: "tcp_close"
    #   syscall: false
    #   args:
    #     - index: 0
    #       type: "sock"
    # - call: "tcp_sendmsg"
    #   syscall: false
    #   args:
    #     - index: 0
    #       type: "sock"
    #     - index: 2
    #       type: int
